import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./component/shared/Navbar";
import { NextUIProvider } from "@nextui-org/react";
import Footer from "./component/shared/Footer";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import { UserProvider } from "./context/UserContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Ryans Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      > 
      <UserProvider>
      <Navbar/>
        <ToastContainer/>
        <NextUIProvider>
          {children}
        </NextUIProvider>
        <Footer></Footer>
      </UserProvider>
        
      </body>
    </html>
  );
}
